# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import kvstore_pb2 as kvstore__pb2


class KeyValueStoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateDirectory = channel.unary_unary(
        '/KeyValueStore/CreateDirectory',
        request_serializer=kvstore__pb2.Empty.SerializeToString,
        response_deserializer=kvstore__pb2.Id.FromString,
        )
    self.UploadFile = channel.stream_unary(
        '/KeyValueStore/UploadFile',
        request_serializer=kvstore__pb2.DataBlock.SerializeToString,
        response_deserializer=kvstore__pb2.UploadStatus.FromString,
        )
    self.Download = channel.unary_stream(
        '/KeyValueStore/Download',
        request_serializer=kvstore__pb2.Id.SerializeToString,
        response_deserializer=kvstore__pb2.DataBlock.FromString,
        )


class KeyValueStoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateDirectory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UploadFile(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Download(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateDirectory': grpc.unary_unary_rpc_method_handler(
          servicer.CreateDirectory,
          request_deserializer=kvstore__pb2.Empty.FromString,
          response_serializer=kvstore__pb2.Id.SerializeToString,
      ),
      'UploadFile': grpc.stream_unary_rpc_method_handler(
          servicer.UploadFile,
          request_deserializer=kvstore__pb2.DataBlock.FromString,
          response_serializer=kvstore__pb2.UploadStatus.SerializeToString,
      ),
      'Download': grpc.unary_stream_rpc_method_handler(
          servicer.Download,
          request_deserializer=kvstore__pb2.Id.FromString,
          response_serializer=kvstore__pb2.DataBlock.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'KeyValueStore', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
