# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import asynctest_pb2 as asynctest__pb2


class HelloWorldStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sayHello = channel.unary_unary(
        '/HelloWorld/sayHello',
        request_serializer=asynctest__pb2.HelloRequest.SerializeToString,
        response_deserializer=asynctest__pb2.HelloResponse.FromString,
        )


class HelloWorldServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sayHello(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HelloWorldServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sayHello': grpc.unary_unary_rpc_method_handler(
          servicer.sayHello,
          request_deserializer=asynctest__pb2.HelloRequest.FromString,
          response_serializer=asynctest__pb2.HelloResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HelloWorld', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
